# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0003_auto_20160211_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='clone_count',
            field=models.IntegerField(default=0),
        ),
    ]
