# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0004_code_clone_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_lang',
            field=models.CharField(default='', max_length=5),
        ),
    ]
