# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0007_auto_20160215_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_lang',
            field=models.CharField(default='C', max_length=15),
        ),
    ]
