# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='user_name',
            field=models.CharField(default='', max_length=11),
        ),
    ]
