# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0002_code_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='last_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
