# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0002_auto_20160210_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='code_lang',
        ),
        migrations.RemoveField(
            model_name='code',
            name='run_count',
        ),
    ]
