# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_lang',
            field=models.CharField(default='xx', max_length=10),
        ),
        migrations.AddField(
            model_name='code',
            name='run_count',
            field=models.IntegerField(default=datetime.datetime(2016, 2, 10, 23, 32, 38, 348004, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
